In [9]:
import numpy as np

In [10]:
def Crout(M):
    a = len(M)
    L = np.zeros([a,a])
    U = np.identity(a)

    for i in range(a):
        for j in range(i+1):
            for h in range(j+1):
                if h == 0:
                    L[i][j] = M[i][j]
                else:
                    L[i][j] = L[i][j] -U[h-1][j]*L[i][h-1]

        for m in range(a-1-i):
            for n in range(i+1):
                if n == 0:
                    U[i][m+1+i] = M[i][m+1+i]/L[i][i]
                else:
                    U[i][m+1+i] = U[i][m+1+i] -(U[n-1][m+1+i]*L[i][n-1]/L[i][i])
    return L,U

In [11]:
def triangular(M):
    n = len(M)
    if n != len(M[0]):
        return 0
    upper = True
    for i in range(n):
        for j in range(i):
            if np.round(M[i][j], 3) !=0:
                upper = False
    lower = True
    for i in range(n):
        a = n-i-1
        for j in range(a):
            b = n-j-1
            if np.round(M[i][b], 3) !=0:
                lower = False
    if lower:
        return 1
    elif upper:
        return 2
    else:
        return 0

In [12]:
def solver(L,U,b):
    # Forward substitution
    if triangular(L) != 1:
        return "L is not a lower triangular matrix"
    n = len(b)
    z = np.zeros(n)
    for i in range(n):
        z[i] = b[i]
        for j in range(i):
            z[i] = z[i]-L[i][j]*z[j]    
        z[i] = z[i]/L[i][i]
    print("z = ", z)
    
    if triangular(U) != 2:
        return "U is not an upper triangular matrix"
    
    # Backward substitution
    y = np.zeros(n)
    for i in range(n):
        a = n-1-i
        y[a] = z[a]
        for j in range(i):
            b = n-1-j
            y[a] = y[a]-U[a][b]*y[b]    
        y[a] = y[a]/U[a][a]
    print("x = ",y)
    return y

In [13]:
s = np.array([[4,3,2], 
              [-2,2,3],
              [3,-5,2]])
b = np.array([25, -10, -4])
L,U = Crout(s)

In [14]:
print(L)

[[ 4.          0.          0.        ]
 [-2.          3.5         0.        ]
 [ 3.         -7.25        8.78571429]]


In [15]:
print(U)

[[1.         0.75       0.5       ]
 [0.         1.         1.14285714]
 [0.         0.         1.        ]]


In [16]:
L.dot(U)

array([[ 4.,  3.,  2.],
       [-2.,  2.,  3.],
       [ 3., -5.,  2.]])

In [18]:
solver(L,U,b)

z =  [ 6.25        0.71428571 -2.        ]
x =  [ 5.  3. -2.]


array([ 5.,  3., -2.])