In [1]:
import numpy as np

In [2]:
def Doolittle(M):
    M = M*1.0
    
    s = len(M)
    
    I = np.identity(len(M))

    for h in range(s-1):
        for i in range(h,s-1):
            if M[i+1][h] != 0:
                num = float(M[i+1][h]/M[h][h])
                I[i+1][h] = num
                for j in range(s):
                    temp = M[i+1][j]
                    M[i+1][j] = temp - (num*M[h][j])
    return I,M

In [3]:
def triangular(M):
    n = len(M)
    if n != len(M[0]):
        return 0
    upper = True
    for i in range(n):
        for j in range(i):
            if np.round(M[i][j], 3) !=0:
                upper = False
    lower = True
    for i in range(n):
        a = n-i-1
        for j in range(a):
            b = n-j-1
            if np.round(M[i][b], 3) !=0:
                lower = False
    if lower:
        return 1
    elif upper:
        return 2
    else:
        return 0

In [4]:
def solver(L,U,b):
    # Forward substitution
    if triangular(L) != 1:
        return "L is not a lower triangular matrix"
    n = len(b)
    z = np.zeros(n)
    for i in range(n):
        z[i] = b[i]
        for j in range(i):
            z[i] = z[i]-L[i][j]*z[j]    
        z[i] = z[i]/L[i][i]
    print("z = ", z)
    
    if triangular(U) != 2:
        return "U is not an upper triangular matrix"
    
    # Backward substitution
    y = np.zeros(n)
    for i in range(n):
        a = n-1-i
        y[a] = z[a]
        for j in range(i):
            b = n-1-j
            y[a] = y[a]-U[a][b]*y[b]    
        y[a] = y[a]/U[a][a]
    print("x = ",y)
    return y

In [5]:
# Solvin a system of equations using LU decomposition
A = np.array([[10,-1,2,0], 
              [-1,11,-1,3],
              [2,-1,10,-1],
              [0,3,-1,8]])
A = A*1.0 # to make it a float
b = np.array([6,25,-11,15])
b= b*1.0

In [6]:
L,U = Doolittle(A)
print(L)
print(U)

[[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]]
[[ 1.00000000e+01 -1.00000000e+00  2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.09000000e+01 -8.00000000e-01  3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  9.54128440e+00 -7.79816514e-01]
 [ 0.00000000e+00 -4.44089210e-16  0.00000000e+00  7.11057692e+00]]


In [8]:
solver(L,U,b)

z =  [  6.          25.6        -10.32110092   7.11057692]
x =  [ 1.  2. -1.  1.]


array([ 1.,  2., -1.,  1.])