In [6]:
import numpy as np

In [7]:
A = np.array([[5,-1,2], 
              [3,8,-2],
              [1,1,4]])

b = np.array([12,-25,6])

A = A*1.0
b = b*1.0

solution = np.linalg.inv(A).dot(b)
print(solution)

[ 1. -3.  2.]


# Gauss-Seidel Method

The **Gauss Seidel Method** is an iterative method that is used solve linear systems of equations. Convergence is guaranteed when the matrix is strictly diagonally dominant. The following function applies this method to solve the system of equations **Ax = b**. It takes as inputs a matrix, a vector **b** and an initial guess **x0**, returning the resulting **x** after the final iteration, and the number of iterations. This function iterates until it reaches consistency to the tolerance $\varepsilon$ using  the **infinity norm** as convergence criteria. The function also takes a boolean pr parameter that is used only to indicate if we want to print the results.

**Infinity Norm**

$l_\infty = \frac{\mid \mid \vec{x}^{(k+1)}-\vec{x}^{(k)}\mid \mid_\infty}{\mid \mid \vec{x}^{(k)}\mid \mid_\infty} < \varepsilon$\\

$\varepsilon$ is the tolerance > 0.

$\mid \mid \vec{x} \mid \mid_\infty = max \mid x_i \mid $ 

$1\leq i \leq n$


In [8]:
def GS(M,b,x,p,pr):
    prev = np.zeros((2,len(M)),float)

    m = len(M)

    inf_norm = 1
    count = 0
    while inf_norm > p :
        for i in range(m):
            prov = b[i]
            for j in range(m):
                if i != j:
                    prov = prov -M[i][j]*x[j]
            x[i] = prov/M[i][i]

        prev[1] = prev[0]
        prev[0] = x

        if count != 0:
            inf_norm = (max(np.absolute(prev[0]-prev[1])))/max(np.absolute(prev[1]))
            if pr:
                print("error = ",inf_norm)
        count = count +1
        if pr:
            print(x)
            print("-----------------")
    return x, count

In [9]:
e = 0.0001
x0 = np.zeros(len(A),float)
pr = True
x, it = GS(A,b,x0,e,pr)
print("Number of iterations = ", it)

[ 2.4     -4.025    1.90625]
-----------------
error =  0.3894409937888198
[ 0.8325     -2.960625    2.03203125]
-----------------
error =  0.054908169727675725
[ 0.9950625  -2.99014062  1.99876953]
-----------------
error =  0.0037091953242168376
[ 1.00246406 -3.00123164  1.99969189]
-----------------
error =  0.0008620289092252939
[ 0.99987691 -3.00003087  2.00003849]
-----------------
error =  3.3838518998848066e-05
[ 0.99997843 -2.99998229  2.00000096]
-----------------
Number of iterations =  6
