In [59]:
import numpy as np

In [60]:
A = np.array([[5,-1,2], 
              [3,8,-2],
              [1,1,4]])

b = np.array([12,-25,6])

A = A*1.0
b = b*1.0

solution = np.linalg.inv(A).dot(b)
print(solution)

[ 1. -3.  2.]


In [61]:
# Jacobi

g = np.array([0.0,0.0,0.0]) # Initial guess
s = np.array([0.0,0.0,0.0]) # one step behind

m = len(A)

for r in range(10):
    for i in range(m):
        prov = b[i]
        for j in range(m):
            if i != j:
                prov = prov -A[i][j]*s[j]
        g[i] = prov/A[i][i]
    s = np.array([g[0],g[1],g[2]]) # Tienes que arreglar estoooooooo
    print(g)

[ 2.4   -3.125  1.5  ]
[ 1.175   -3.65     1.68125]
[ 0.9975    -3.1453125  2.11875  ]
[ 0.9234375  -2.969375    2.03695313]
[ 0.99134375 -2.96205078  2.01148437]
[ 1.00299609 -2.99388281  1.99267676]
[ 1.00415273 -3.00295435  1.99772168]
[ 1.00032046 -3.00212686  1.9997004 ]
[ 0.99969447 -3.00019507  2.0004516 ]
[ 0.99978035 -2.99977253  2.00012515]
