In [15]:
import numpy as np

In [16]:
A = np.array([[2,4,3,5], 
              [-4,-7,-5,-8],
              [6,8,2,9],
              [4,9,-2,14]])


I = np.array([[1,0,0,0], 
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,1]])

s = len(A)

for h in range(s-1):
    for i in range(h,s-1):
        if A[i+1][h] != 0:
            num = float(A[i+1][h]/A[h][h])
            I[i+1][h] = num
            for j in range(s):
                temp = A[i+1][j]
                A[i+1][j] = temp - (num*A[h][j])
L = I
U = A

In [17]:
print(U)

[[ 2  4  3  5]
 [ 0  1  1  2]
 [ 0  0 -3  2]
 [ 0  0  0 -4]]


In [18]:
print(L)

[[ 1  0  0  0]
 [-2  1  0  0]
 [ 3 -4  1  0]
 [ 2  1  3  1]]


In [19]:
# Es mejor inicializar A como float, si no te dara L U con puros integers siempre aunque no sea el caso
A = np.array([[2.0,-1.0,1.0], 
              [3.0,3.0,9.0],
              [3.0,3.0,5.0]])


I = np.array([[1.0,0,0], 
              [0,1.0,0],
              [0,0,1.0]])

s = len(A)

for h in range(s-1):
    for i in range(h,s-1):
        if A[i+1][h] != 0:
            num = float(A[i+1][h]/A[h][h])
            I[i+1][h] = num
            for j in range(s):
                temp = A[i+1][j]
                A[i+1][j] = temp - (num*A[h][j])
L = I
U = A

In [20]:
print(U)

[[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


In [21]:
print(L)

[[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]


In [22]:
L.dot(U)

array([[ 2., -1.,  1.],
       [ 3.,  3.,  9.],
       [ 3.,  3.,  5.]])

In [23]:
# Solvin a system of equations using LU decomposition
A = np.array([[10,-1,2,0], 
              [-1,11,-1,3],
              [2,-1,10,-1],
              [0,3,-1,8]])
A = A*1.0 # to make it a float
b = np.array([6,25,-11,15])
b= b*1.0



In [24]:
I = np.array([[1,0,0,0], 
              [0,1,0,0],
              [0,0,1,0],
              [0,0,0,1]])


I= I*1.0
s = len(A)

for h in range(s-1):
    for i in range(h,s-1):
        if A[i+1][h] != 0:
            num = float(A[i+1][h]/A[h][h])
            I[i+1][h] = num
            for j in range(s):
                temp = A[i+1][j]
                A[i+1][j] = temp - (num*A[h][j])

In [25]:
print(A)
print("----------")
print(I)

L = I
U = A

[[ 1.00000000e+01 -1.00000000e+00  2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.09000000e+01 -8.00000000e-01  3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  9.54128440e+00 -7.79816514e-01]
 [ 0.00000000e+00 -4.44089210e-16  0.00000000e+00  7.11057692e+00]]
----------
[[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]]


In [26]:
L.dot(U) # Comprobando que esten bien

array([[10., -1.,  2.,  0.],
       [-1., 11., -1.,  3.],
       [ 2., -1., 10., -1.],
       [ 0.,  3., -1.,  8.]])

In [27]:
z = np.linalg.inv(L).dot(b)
print(z)

[  6.          25.6        -10.32110092   7.11057692]


In [28]:
y = np.linalg.inv(U).dot(z)
print(y)

[ 1.  2. -1.  1.]


In [46]:
def diagonallyDom(M):
    m = len(M)
    for i in range(m):
        D = np.absolute(M[i][i])
        suma = 0
        for j in range(m):
            if i != j:
                suma = suma + np.absolute(M[i][j])
        if D <= suma:
            return False
            
    return True

In [55]:
A = np.array([[10,-1,2,0], 
              [-1,11,-1,3],
              [2,-1,10,-1],
              [0,3,-1,8]])
A = A*1.0 # to make it a float

In [56]:
def LU(M):
    M = M*1.0 # to make it a float
    if not diagonallyDom(M):
        return "The Matrix is not diagonally dominant"
    
    s = len(M)
    
    I = np.identity(len(M))

    for h in range(s-1):
        for i in range(h,s-1):
            if M[i+1][h] != 0:
                num = float(M[i+1][h]/M[h][h])
                I[i+1][h] = num
                for j in range(s):
                    temp = M[i+1][j]
                    M[i+1][j] = temp - (num*M[h][j])
    return I,M

In [58]:
L,U = LU(A)
print(L)
print(U)

[[ 1.          0.          0.          0.        ]
 [-0.1         1.          0.          0.        ]
 [ 0.2        -0.0733945   1.          0.        ]
 [ 0.          0.27522936 -0.08173077  1.        ]]
[[ 1.00000000e+01 -1.00000000e+00  2.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.09000000e+01 -8.00000000e-01  3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  9.54128440e+00 -7.79816514e-01]
 [ 0.00000000e+00 -4.44089210e-16  0.00000000e+00  7.11057692e+00]]
